Repository hmcts/ccpay-payment-app, pull requests merged in 2020-06, with the labels that each got.

#693 chart version publish for IAC on boarding
  api/src/main/resources/application-local.properties
  api/src/main/resources/application.properties
  api/src/test/resources/application-componenttest.properties
  charts/payment-api/Chart.yaml
  charts/payment-api/values.yaml
  docker-compose.yml
Labels: ns:fees-pay, rel:payment-api-pr-693

#695 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-695

#698 Pay 3392- cpu core increase
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-698

#699 Updating database cpu cores from 2 to 4 in demo for testing
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-699

#700 Updating database cpu cores from 2 to 4 in demo for testing
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-700

#701 remove unused imports and some clean up
  api/src/main/java/uk/gov/hmcts/payment/api/configuration/SecurityUtils.java
  api/src/main/java/uk/gov/hmcts/payment/api/configuration/security/SpringSecurityConfiguration.java
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-701
