Repository hmcts/ccpay-payment-app, pull requests merged in 2020-11, with the labels that each got.

#787 IAC PBA chart changes for prod
  charts/payment-api/Chart.yaml
  charts/payment-api/values.yaml
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-787

#784 TA-151: Extend test scenarios for Divorce
  api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CardPaymentProviderTest.java
  api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTest.java
  api/src/contractTest/java/uk/gov/hmcts/payment/api/controllers/provider/CreditAccountPaymentProviderTestConfiguration.java
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-784

#780 PAY-3704- Terraform version upgrade 13
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/versions.tf
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-780

#782 Pay 3763 payment api docker
  docker-compose.yml
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-782

#790 supression added for CVE-2020-15250
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-790
