Repository hmcts/ccpay-payment-app, pull requests merged in 2020-05, with the labels that each got.

#670 Pay-2865-publish chart
  charts/payment-api/Chart.yaml
  charts/payment-api/values.preview.template.yaml
  charts/payment-api/values.yaml
  dependency-check-suppressions.xml
Labels: ns:fees-pay, rel:payment-api-pr-670

#672 PAY-2736: AKS migration & pba reporting
  api/src/main/resources/bootstrap.yaml
  charts/payment-api/Chart.yaml
  charts/payment-api/values.yaml
  dependency-check-suppressions.xml
Labels: ns:fees-pay, rel:payment-api-pr-672

#677 Removed ASE infrastructure
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/perftest.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, rel:payment-api-pr-677

#680 Revert "work around fees and pay deployment"
  Jenkinsfile_CNP
Labels: ns:fees-pay, rel:payment-api-pr-680

#686 OIDC audience list updated.
  charts/payment-api/Chart.yaml
  charts/payment-api/values.yaml
  dependency-check-suppressions.xml
Labels: ns:fees-pay, rel:payment-api-pr-686

#685 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
  dependency-check-suppressions.xml
Labels: ns:fees-pay, rel:payment-api-pr-685

#690 PAY-3261
  dependency-check-suppressions.xml
Labels: ns:fees-pay, rel:payment-api-pr-690
