Repository hmcts/ccpay-payment-app, pull requests merged in 2022-04, with the labels that each got.

#1162 cve supress
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1162

#1169 cve fix+suppression date extended
  api/build.gradle
  cve-resolution-strategy.gradle
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1169

#1172 CVE-2022-22965 -suppressed
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1172
