Repository hmcts/ccpay-payment-app, pull requests merged in 2023-12, with the labels that each got.

#1544 PAY-6723: Fix SDP Config in ITHC and PerfTest
  api/build.gradle
  dependency-check-suppressions.xml
  infrastructure/sdp.tf
Labels: ns:fees-pay, prd:payment, no-changes, rel:payment-api-pr-1544

#1546 Pay 6723 final sdp fix
  infrastructure/sdp.tf
Labels: ns:fees-pay, prd:payment, destroy, rel:payment-api-pr-1546

#1547 PAY-6746 logback
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1547

#1548 PAY-6746 remove old references to logback
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1548

#1549 PAY-6659 decommission v11 database
  charts/payment-api/Chart.yaml
  charts/payment-api/values.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:payment, destroy, rel:payment-api-pr-1549

#1550 PAY-6756 owasp upgrade
  build.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1550
