Repository hmcts/ccpay-payment-app, pull requests merged in 2023-09, with the labels that each got.

#1490 PAY-6510: Nightly build pipeline fixes
  audit.json
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1490

#1491 CVE-2023-41080 Surpression fix
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1491

#1504 version reversion
  api/build.gradle
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1504

#1506 PAY-6543: Payments API Renovate Update Backend
  .github/renovate.json
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1506
