Repository hmcts/ccpay-payment-app, pull requests merged in 2025-06, with the labels that each got.

#1803 PAY-7859
  dependency-check-suppressions.xml
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1803

#1784 CME-126 add db monitoring action group
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:fees-pay, prd:payment, aat/destroy, prod/destroy, rel:payment-api-pr-1784

#1795 CME-529 replace jitpack with azure artifactory
  api/build.gradle
  api/src/main/java/uk/gov/hmcts/payment/api/configuration/RestTemplateConfiguration.java
  build.gradle
  jitpack.yml
  model/build.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1795
