Repository hmcts/ccpay-payment-app, pull requests merged in 2025-07, with the labels that each got.

#1812 PAY-7850: Update APIM Policy to use named values
  infrastructure/cft-api-mgmt.tf
  infrastructure/template/cft-api-policy.xml
Labels: ns:fees-pay, prd:payment, aat/add-or-update, prod/add-or-update, rel:payment-api-pr-1812

#1837 https://tools.hmcts.net/jira/browse/PAY-7980
  audit.json
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1837

#1844 PAY-7984 commons-lang3 cve
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1844

#1845 PAY-7984 tomcat cve
  cve-resolution-strategy.gradle
Labels: ns:fees-pay, prd:payment, rel:payment-api-pr-1845
